run:
  go: "1.23"
  concurrency: 8
  timeout: 10m

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - prealloc
    - reassign
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace