version: "2"

run:
    go: "1.24"
    concurrency: 8
    timeout: 10m

linters:
    default: none
    enable:
        - asasalint
        - asciicheck
        - errcheck
        - gofmt
        - goimports
        - gomodguard
        - goprintffuncname
        - govet
        - ineffassign
        - misspell
        - nakedret
        - nolintlint
        - prealloc
        - reassign
        - staticcheck
        - typecheck
        - unconvert
        - unused
        - whitespace
