method: "GET"
url: "https://example.com"
yes: false
timeout: "5s"
dodos: 8
requests: 1000
duration: "10s"
skip_verify: false

params:
    - key1: ["value1", "value2", "value3", "value4"]
    - key1: "value"
    - key2: ["value1", "value2"]

headers:
    - key1: ["value1", "value2", "value3", "value4"]
    - key1: "value"
    - key2: ["value1", "value2"]

cookies:
    - key1: ["value1", "value2", "value3", "value4"]
    - key1: "value"
    - key2: ["value1", "value2"]

# body: "body-text"
# OR
# A random body value will be selected from the list for each request
body:
    - "body-text1"
    - "body-text2"
    - "body-text3"

# proxy: "http://example.com:8080"
# OR
# A random proxy will be selected from the list for each request
proxy:
    - "http://example.com:8080"
    - "http://username:password@example.com:8080"
    - "socks5://example.com:8080"
    - "socks5h://example.com:8080"
